version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/post:${VERSION_POST:-1.0}
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/comment:${VERSION_COMMENT:-1.0}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/ui:${VERSION_UI:-2.0}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
