version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file: .env
    image: ${USER_NAME}/post:${VERSION_POST:-1.0}
    ports:
      - 9292:9292/tcp
    networks:
      - back_net
      - front_net
  post:
    env_file: .env
    image: ${USER_NAME}/comment:${VERSION_COMMENT:-1.0}
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    image: ${USER_NAME}/ui:${VERSION_UI:-2.0}
    networks:
      - front_net

  prometheus:
    image: ${USER_NAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
