kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: uOUN9BwRIDGJ334t510isycmsbDCE5aTS2D2AUzjl/A=
      - identity: {}
