version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO:-3.2}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/post:${VERSION_POST:-1.0}
    ports:
      - 9292:9292/tcp
    networks:
      - back_net
      - front_net
    command: 'puma --debug -w 2'
  post:
    build: ./post-py
    image: ${USERNAME}/comment:${VERSION_COMMENT:-1.0}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/ui:${VERSION_UI:-2.0}
    networks:
      - front_net
    command: 'puma --debug -w 2'

volumes:
  post_db:

networks:
  back_net:
  front_net:
